export const teams = [
    "總召",
    "行銷",
    "人資",
    "財務",
    "視覺",
    "網管",
    "公關",
    "演講",
    "攝影",
    "技術教學",
    "設計教學",
    "設計 TA",
    "技術 TA",
]

export const students = [
    {
        id: 1,
        team: '總召',
        name: 'A Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 2,
        team: '行銷',
        name: 'B Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 3,
        team: '人資',
        name: 'C Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 4,
        team: '財務',
        name: 'D Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 5,
        team: '視覺',
        name: 'E Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 6,
        team: '網管',
        name: 'F Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 7,
        team: '公關',
        name: 'G Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 8,
        team: '演講',
        name: 'H Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 9,
        team: '攝影',
        name: 'I Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 10,
        team: '技術教學',
        name: 'J Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 11,
        team: '設計教學',
        name: 'K Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 12,
        team: '設計 TA',
        name: 'L Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    },
    {
        id: 13,
        team: '技術 TA',
        name: 'M Doe',
        school: 'ABC School',
        department: 'Computer Science',
        image: '/images/album-cover.png',
    }
]